class SurtrException(Exception): ...
class UrlParseError(SurtrException): ...
class NoSchemeFoundError(SurtrException): ...
class CanonicalizerError(SurtrException): ...

def surt(url: str | bytes, **kwargs: bool) -> str | bytes: ...
